config/routes.rb
Rails.application.routes.draw do
  get 'talkrooms/show'
  post 'member_chats/new' => 'member_chats#new'
  devise_for :receivers, controllers: {   registrations: 'receivers/registrations',
                                          sessions: 'receivers/sessions' }

  devise_for :advisors, controllers: {   registrations: 'advisors/registrations',
                                         sessions: 'advisors/sessions' }

  root to: "posts#toppage"
  resources :member_chats, only: [:index, :new, :create, :show]
  resources :receivers, only: [:show]
  resources :talkrooms, :only => [:show, :create] do
    resources :messages, :only => [:create]

end
end

app/models/member_chat.rb
class MemberChat < ApplicationRecord
  belongs_to :receiver, optional: true
  belongs_to :advisor, optional: true

  validates :content, presence: true, unless: :image?

  mount_uploader :image, ImageUploader
end

app/controllers/member_chats_controller.rb
class MemberChatsController < ApplicationController
  def new
    @member_chat = MemberChat.new 
  end

  def create
    if receiver_signed_in?
      @member_chat = MemberChat.new(member_chat_params)  
      @member_chat.receiver_id = current_receiver.id 
      # @member_chat.advisor_id = current_advisor.id 
      @member_chat.save
      redirect_to member_chats_path
    # elsif advisor_signed_in?
    #   @member_chat = MemberChat.new(member_chat_params)  
    #   @member_chat.advisor_id = current_advisor.id 
    #   @member_chat.save
    #   redirect_to member_chats_path
    end
  end

  def index
    @member_chats = MemberChat.all
    # if receiver_signed_in?
    #   @advisors = Advisor.all
    #   talkrooms = current_receiver.talkrooms
    #   @advisor_ids = []
    #   talkrooms.each do |r|
    #     @advisor_ids << r.advisor_id
    #   end

    # elsif advisor_signed_in?
    #   @receivers = Receiver.all
    #   talkrooms = current_advisor.talkrooms
    #   @receiver_ids = []
    #   talkrooms.each do |r|
    #     @receiver_ids << r.receiver_id
    #   end
    # end
  end

  def show
    @member_chat = MemberChat.find(params[:id])
    @receiver = @member_chat.receiver
    if receiver_signed_in?
      @advisors = Advisor.all
      talkrooms = current_receiver.talkrooms
      @advisor_ids = []
      talkrooms.each do |r|
        @advisor_ids << r.advisor_id
      end

    elsif advisor_signed_in?
      @receivers = Receiver.all
      talkrooms = current_advisor.talkrooms
      @receiver_ids = []
      talkrooms.each do |r|
        @receiver_ids << r.receiver_id
      end
    end
  end
    
  private
    def member_chat_params
      params.require(:member_chat).permit(:content, :image)
      # .merge(receiver_id: current_receiver.id, advisor_id: current_advisor.id)
    end

end

app/helpers/member_chats_helper.rb
module MemberChatsHelper
end

app/views/member_chats/index.html.haml
.top
  - if receiver_signed_in?
    %strong= link_to current_receiver.name
    = link_to 'プロフィール変更', edit_receiver_registration_path, class: "receiver_left"
    = link_to 'ログアウト', destroy_receiver_session_path, method: :delete
    = link_to '投稿', new_member_chat_path

    - @member_chats.each do |member_chat|
      %hr/
      %p
      %span 投稿内容: 
      = link_to member_chat.content
      = link_to member_chat.receiver.name, member_chat_path(member_chat.id)

  - elsif advisor_signed_in?
    %strong= link_to current_advisor.name
    = link_to 'プロフィール変更', edit_advisor_registration_path
    = link_to 'ログアウト', destroy_advisor_session_path, method: :delete, class: "advisor_right"
    -# = link_to '投稿', new_member_chat_path

    - @member_chats.each do |member_chat|
      %hr/
      %p
      %span 投稿内容: 
      = link_to member_chat.content
      = link_to member_chat.receiver.name, member_chat_path(member_chat.id)

app/views/member_chats/new.html.haml
= form_with(model: @member_chat, local: true) do |f|
  = f.text_field :content
  = f.submit "投稿"

app/views/member_chats/show.html.haml
%h1 プロフィール
%p
  名前 : #{@receiver.name}
%p 
  性別 : #{@receiver.gender}

- if receiver_signed_in?
  - @advisors.each do |advisor|
    - if @advisor_ids.include?(advisor.id)
      %br/
      = link_to "チャットへ", talkroom_path(current_receiver.talkrooms.find_by(advisor_id: advisor.id))
      %br/
    - else
      = form_for Talkroom.new do |f|
        = f.hidden_field :advisor_id, :value => advisor.id
        = f.submit
- elsif advisor_signed_in?
  - @receivers.each do |receiver|
    - if @receiver_ids.include?(receiver.id)
      %br/
      = link_to "チャットへ", talkroom_path(current_advisor.talkrooms.find_by(receiver_id: receiver.id))
      %br/
    - else
      = form_for Talkroom.new do |f|
        = f.hidden_field :receiver_id, :value => receiver.id
        = f.submit
   