config/routes.rb
Rails.application.routes.draw do
  get 'talkrooms/show'
  post 'member_chats/new' => 'member_chats#new'
  devise_for :receivers, controllers: {   registrations: 'receivers/registrations',
                                          sessions: 'receivers/sessions' }

  devise_for :advisors, controllers: {   registrations: 'advisors/registrations',
                                         sessions: 'advisors/sessions' }

  root to: "posts#toppage"
  resources :member_chats, only: [:index, :new, :create, :show]
  resources :receivers, only: [:show]
  resources :talkrooms, :only => [:show, :create] do
    resources :messages, :only => [:create]

end
end

app/models/talkroom.rb
class Talkroom < ApplicationRecord
  belongs_to :receiver
  belongs_to :advisor

  has_many :messages
end

app/controllers/talkrooms_controller.rb
class TalkroomsController < ApplicationController
  def show
    @talkroom = Talkroom.find(params[:id]) 
    @message = Message.new 
    @messages = @talkroom.messages 
    if receiver_signed_in?
      if @talkroom.receiver.id == current_receiver.id
        @advisor = @talkroom.advisor
      else
        redirect_to root_path
      end
    elsif advisor_signed_in?
      if @talkroom.advisor.id == current_advisor.id
        @receiver = @talkroom.receiver
      else
        redirect_to root_path
      end

    else
      redirect_to root_path
    end

  end

  def create
    if receiver_signed_in?
      @talkroom = Talkroom.new(talkroom_advisor_params)
      @talkroom.receiver_id = current_receiver.id
    elsif advisor_signed_in?
      @talkroom = Talkroom.new(talkroom_receiver_params)
      @talkroom.advisor_id = current_advisor.id
    else
      redirect_to root_path
    end

    if @talkroom.save
      redirect_to :action => "show", :id => @talkroom.id
    else
      redirect_to root_path
    end
  end

  private
  def talkroom_advisor_params
    params.require(:talkroom).permit(:advisor_id)
  end

  def talkroom_receiver_params
    params.require(:talkroom).permit(:receiver_id)
  end

end

app/helpers/talkrooms_helper.rb
module TalkroomsHelper
end

app/views/talkrooms/show.html.haml
%h5
  = link_to "メッセージするユーザーを選択し直す", member_chats_path
 
%h2 トークルーム
- if receiver_signed_in?
  %h3
    - @advisor.name
    とのチャットルーム
  .chat-field
    - @messages.each do |m|
      - if m.is_receiver
        .right-message
          = m.content
          = m.image
      - else
        .left-message
          = m.content
          = m.image
- elsif advisor_signed_in?
  %h3
    - @receiver.name
    とのチャットルーム
  .chat-field
    - @messages.each do |m|
      - if m.is_receiver
        .left-message
          = m.content
          = m.image
      - else
        .right-message
          = m.content
          = m.image
= form_for [@talkroom, @message] do |f|
  = f.text_field :content
  = f.file_field :image
  = f.submit "メッセージを送る"