config/routes.rb
Rails.application.routes.draw do
  get 'talkrooms/show'
  post 'member_chats/new' => 'member_chats#new'
  devise_for :receivers, controllers: {   registrations: 'receivers/registrations',
                                          sessions: 'receivers/sessions' }

  devise_for :advisors, controllers: {   registrations: 'advisors/registrations',
                                         sessions: 'advisors/sessions' }

  root to: "posts#toppage"
  resources :member_chats, only: [:index, :new, :create, :show]
  resources :receivers, only: [:show]
  resources :talkrooms, :only => [:show, :create] do
    resources :messages, :only => [:create]

end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def toppage
  end

end

app/views/posts/test.html.haml
.frame
  .plane-container
    %a{:href => "http://customer.io/", :target => "_blank"}
      %svg.plane{"enable-background" => "new 0 0 1131.53 379.304", :height => "379.304px", :version => "1.1", :viewbox => "0 0 1131.53 379.304", :width => "1131.53px", :x => "0px", "xml:space" => "preserve", :xmlns => "http://www.w3.org/2000/svg", "xmlns:xlink" => "http://www.w3.org/1999/xlink", :y => "0px"}
        %polygon{:fill => "#D8D8D8", :points => "72.008,0 274.113,140.173 274.113,301.804 390.796,221.102 601.682,367.302 1131.53,0.223  "}
        %polygon{:fill => "#C4C4C3", :points => "1131.53,0.223 274.113,140.173 274.113,301.804 390.796,221.102   "}
.clouds
  %svg.cloud.big.front.slowest{"enable-background" => "new 0 0 762 331", :height => "331px", :version => "1.1", :viewbox => "0 0 762 331", :width => "762px", :x => "0px", "xml:space" => "preserve", :xmlns => "http://www.w3.org/2000/svg", "xmlns:xlink" => "http://www.w3.org/1999/xlink", :y => "0px"}
    %path{:d => "M715.394,228h-16.595c0.79-5.219,1.201-10.562,1.201-16c0-58.542-47.458-106-106-106\nc-8.198,0-16.178,0.932-23.841,2.693C548.279,45.434,488.199,0,417.5,0c-84.827,0-154.374,65.401-160.98,148.529\nC245.15,143.684,232.639,141,219.5,141c-49.667,0-90.381,38.315-94.204,87H46.607C20.866,228,0,251.058,0,279.5\nS20.866,331,46.607,331h668.787C741.133,331,762,307.942,762,279.5S741.133,228,715.394,228z", :fill => "#FFFFFF"}
  %svg.cloud.distant.smaller{"enable-background" => "new 0 0 762 331", :height => "331px", :version => "1.1", :viewbox => "0 0 762 331", :width => "762px", :x => "0px", "xml:space" => "preserve", :xmlns => "http://www.w3.org/2000/svg", "xmlns:xlink" => "http://www.w3.org/1999/xlink", :y => "0px"}
    %path{:d => "M715.394,228h-16.595c0.79-5.219,1.201-10.562,1.201-16c0-58.542-47.458-106-106-106\nc-8.198,0-16.178,0.932-23.841,2.693C548.279,45.434,488.199,0,417.5,0c-84.827,0-154.374,65.401-160.98,148.529\nC245.15,143.684,232.639,141,219.5,141c-49.667,0-90.381,38.315-94.204,87H46.607C20.866,228,0,251.058,0,279.5\nS20.866,331,46.607,331h668.787C741.133,331,762,307.942,762,279.5S741.133,228,715.394,228z", :fill => "#FFFFFF"}
  %svg.cloud.small.slow{"enable-background" => "new 0 0 762 331", :height => "331px", :version => "1.1", :viewbox => "0 0 762 331", :width => "762px", :x => "0px", "xml:space" => "preserve", :xmlns => "http://www.w3.org/2000/svg", "xmlns:xlink" => "http://www.w3.org/1999/xlink", :y => "0px"}
    %path{:d => "M715.394,228h-16.595c0.79-5.219,1.201-10.562,1.201-16c0-58.542-47.458-106-106-106\nc-8.198,0-16.178,0.932-23.841,2.693C548.279,45.434,488.199,0,417.5,0c-84.827,0-154.374,65.401-160.98,148.529\nC245.15,143.684,232.639,141,219.5,141c-49.667,0-90.381,38.315-94.204,87H46.607C20.866,228,0,251.058,0,279.5\nS20.866,331,46.607,331h668.787C741.133,331,762,307.942,762,279.5S741.133,228,715.394,228z", :fill => "#FFFFFF"}
  %svg.cloud.distant.super-slow.massive{"enable-background" => "new 0 0 762 331", :height => "331px", :version => "1.1", :viewbox => "0 0 762 331", :width => "762px", :x => "0px", "xml:space" => "preserve", :xmlns => "http://www.w3.org/2000/svg", "xmlns:xlink" => "http://www.w3.org/1999/xlink", :y => "0px"}
    %path{:d => "M715.394,228h-16.595c0.79-5.219,1.201-10.562,1.201-16c0-58.542-47.458-106-106-106\nc-8.198,0-16.178,0.932-23.841,2.693C548.279,45.434,488.199,0,417.5,0c-84.827,0-154.374,65.401-160.98,148.529\nC245.15,143.684,232.639,141,219.5,141c-49.667,0-90.381,38.315-94.204,87H46.607C20.866,228,0,251.058,0,279.5\nS20.866,331,46.607,331h668.787C741.133,331,762,307.942,762,279.5S741.133,228,715.394,228z", :fill => "#FFFFFF"}
  %svg.cloud.slower{"enable-background" => "new 0 0 762 331", :height => "331px", :version => "1.1", :viewbox => "0 0 762 331", :width => "762px", :x => "0px", "xml:space" => "preserve", :xmlns => "http://www.w3.org/2000/svg", "xmlns:xlink" => "http://www.w3.org/1999/xlink", :y => "0px"}
    %path{:d => "M715.394,228h-16.595c0.79-5.219,1.201-10.562,1.201-16c0-58.542-47.458-106-106-106\nc-8.198,0-16.178,0.932-23.841,2.693C548.279,45.434,488.199,0,417.5,0c-84.827,0-154.374,65.401-160.98,148.529\nC245.15,143.684,232.639,141,219.5,141c-49.667,0-90.381,38.315-94.204,87H46.607C20.866,228,0,251.058,0,279.5\nS20.866,331,46.607,331h668.787C741.133,331,762,307.942,762,279.5S741.133,228,715.394,228z", :fill => "#FFFFFF"}

app/views/posts/toppage.html.haml
.wrapper
  .header
    .header__main
      .header__main__top
        %p
          %span
            producteur  
            

    .header__sub
      .header__sub__1
        - if receiver_signed_in?
          %strong= link_to current_receiver.name,page_class
          -# , pages_show_path
          = link_to 'プロフィール変更', edit_receiver_registration_path, class: "receiver_left"
          = link_to 'ログアウト', destroy_receiver_session_path, method: :delete
        - elsif advisor_signed_in?
          %strong= link_to current_advisor.name,page_class
          -# , pages_show_path
          = link_to 'プロフィール変更', edit_advisor_registration_path
          = link_to 'ログアウト', destroy_advisor_session_path, method: :delete, class: "advisor_right"
        - else
          %i.fas.fa-user
          一般の方
          = link_to 'サインアップ', new_receiver_registration_path, class: "receiver_left"
          = link_to 'ログイン', new_receiver_session_path
          %i.fas.fa-user-tie
          美容職の方
          = link_to 'サインアップ', new_advisor_registration_path
          = link_to 'ログイン', new_advisor_session_path, class: "advisor_right"

  .body
    .body__main
      %b Our mission 
      .body__main__top
        %d プロの手で史上最高のあなたにすること
      .body__main__top
        %d 美容のプロと気軽に相談できる場を提供すること
      .body__main__top
        %d お客様目線でやりとりできる場を提供すること
    .body__sub
      %c Howーto
      .body__sub__bottom
        .body__sub__bottom__plus
          今気になっていることや悩んでいることをメンバーチャットでつぶやいてみる。（例：①前髪失敗しました！  ②今期オススメの赤色のリップ知りたい！   、、、etc）
        .body__sub__bottom__plus
          美容師や美容部員の方からつぶやきに対してメッセージが来た時点でやりとりスタートです。（例：①前髪の大得意です！  ②今期のオススメは〇〇です！   、、、etc）
        .body__sub__bottom__plus
          気に入った方やお店があれば、そのままご予約いただくことも可能です。

  .footer
    %i.far.fa-bell 注意事項
    .footer__plus
      %li 基本的には、チャットにつぶやいてそれに対してのメッセージが来るのを待つ形になります。
      %li オンライン上でのやりとりがメインなので、個人情報のやりとりにはご注意ください。
      %li お互いに気持ちの良いやりとりをしていただくために、虚偽の申告等はしないようにお願いします。
      %li メッセージでやり取りしていただいて、そのまま施術の予約をしていただくこともできます。
      %li 匿名でご登録いただいて使用することも可能です。(予約等される場合は、本人名義が必要になります
    